name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Check out omnetpp
      uses: actions/checkout@v3
      with:
        repository: omnetpp/omnetpp
        path: omnetpp
        ref: omnetpp-5.7.x
    
    - name: Install debs
      run: sudo apt-get install -y qt6-base-dev qt5-qmake
    
    - name: Init omnetpp
      run: |
        source omnetpp/setenv
        cd omnetpp/
        ./configure

    - name: configure
      run: make makefiles

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
