name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        path: castalia
    
    - name: Check out omnetpp
      uses: actions/checkout@v3
      with:
        repository: omnetpp/omnetpp
        path: omnetpp
        ref: omnetpp-5.7.x
    - name: Update ubuntu
      run: sudo apt update
    
    - name: Install debs
      run: sudo apt-get install -y libqt5concurrent5 libqt5core5a libqt5dbus5 
           libqt5gui5 libqt5multimedia5-plugins libqt5multimedia5 libqt5multimediagsttools5
           libqt5multimediawidgets5 libqt5network5 libqt5opengl5-dev libqt5opengl5 libqt5printsupport5
           libqt5qml5 libqt5qmlmodels5 libqt5quick5 libqt5sql5-sqlite libqt5sql5 libqt5svg5 libqt5test5
           libqt5waylandclient5 libqt5waylandcompositor5 libqt5widgets5 libqt5x11extras5 libqt5xml5 qt5-gtk-platformtheme
           qt5-qmake-bin qt5-qmake libyaml-cpp-dev
           
    - name: Install sanps
      run: sudo snap install yq
  
    - name: Init omnetpp
      run: |
        source omnetpp/setenv
        cd omnetpp/
        echo "WITH_OSG=no" >> configure.user
        echo "WITH_QTENV=no" >> configure.user
        echo "WITH_NETBUILDER=yes" >> configure.user
        ./configure
        make

    - name: Configure Castalia
      run: |
        source omnetpp/setenv
        cd castalia
        ./make_wo_efmrp.sh

    - name: Compile Castalia
      run: |
        source omnetpp/setenv
        cd castalia
        make
    
    - name: Test Castalia
      run: |
        source omnetpp/setenv
        cd castalia/Simulations/shmrp_nf
        ./batch.sh

    - name: Show logs
      if: always()
      run: |
        cd castalia/Simulations/shmrp_nf
        tail Castalia-Trace.txt
